# Generated by Django 4.2.13 on 2024-05-31 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField()),
                ('project_link', models.CharField(max_length=100, unique=True)),
                ('tmpdir', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('python_code', models.TextField()),
                ('intermediate', models.TextField()),
                ('sb3_json', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['project_link'], name='converter_c_project_4b1523_idx')],
            },
        ),
    ]
