# Generated by Django 4.2.13 on 2024-05-31 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_conversion_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='sb3_file_name',
            field=models.TextField(default='bla'),
            preserve_default=False,
        ),
    ]
