# Generated by Django 4.1.2 on 2024-06-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0003_conversion_sb3_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversion",
            name="scratch_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
